apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-service-storage-pvc
  labels:
    app: order-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
