apiVersion: v1
kind: Pod
metadata:
  name: pending-demo-fixed
  labels:
    app: pending-demo
spec:
  containers:
  - name: heavy-app
    image: nginx:alpine
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
