apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - port: 80
    targetPort: 80
  # Correct matching selector matching the pod template labels
  selector:
    app: backend-app
