apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-processing-gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sambhavbohra/DevOps.git'
    targetRevision: HEAD
    path: 'Session 20 - Monitoring, Observability & GitOps/03-gitops-demo/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
