apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-devops-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sambhavbohra/DevOps.git'
    targetRevision: HEAD
    path: 'Session 21 - Final DevOps Project & Troubleshooting/final-devops-project/kubernetes'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kubernetes/deployment.yaml
  - ../kubernetes/configmap.yaml
