apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-web.fullname" . }}-config
  labels:
    {{- include "ecommerce-web.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  API_URL: {{ .Values.config.API_URL | quote }}
  ENABLE_FEATURE_FLAGS: {{ .Values.config.ENABLE_FEATURE_FLAGS | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-web.fullname" . }}-secret
  labels:
    {{- include "ecommerce-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | quote }}
